# Generated by Django 4.2.20 on 2025-04-01 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_observation_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterCode',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Код показателя')),
                ('name', models.CharField(max_length=255, verbose_name='Название показателя')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Код показателя',
                'verbose_name_plural': 'Коды показателей',
            },
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['patient', 'parameter', '-timestamp'], 'verbose_name': 'Наблюдение (показатель)', 'verbose_name_plural': 'Наблюдения (показатели)'},
        ),
        migrations.RemoveIndex(
            model_name='observation',
            name='core_observ_patient_27e925_idx',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='observation_time',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='observation_type',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='value_text',
        ),
        migrations.AddField(
            model_name='observation',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто записал'),
        ),
        migrations.AddField(
            model_name='observation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observation',
            name='value',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Значение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observation',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hospitalizationepisode', verbose_name='Эпизод госпитализации'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='value_numeric',
            field=models.FloatField(blank=True, null=True, verbose_name='Числовое значение (если применимо)'),
        ),
        migrations.AddField(
            model_name='observation',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='core.parametercode', verbose_name='Показатель'),
        ),
    ]
