# Generated by Django 4.2.20 on 2025-04-02 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parametercode_alter_observation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MKBCode',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Код МКБ')),
                ('name', models.TextField(verbose_name='Название диагноза')),
            ],
            options={
                'verbose_name': 'Код МКБ',
                'verbose_name_plural': 'Коды МКБ',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='clinic_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID в клинике'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='primary_diagnosis_mkb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_with_primary_diagnosis', to='core.mkbcode', verbose_name='Первичный диагноз (МКБ)'),
        ),
    ]
