# Generated by Django 4.2.20 on 2025-04-04 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_medicaltest_delete_observationtype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalizationepisode',
            options={'ordering': ['patient', '-start_date'], 'verbose_name': 'Эпизод госпитализации', 'verbose_name_plural': 'Эпизоды госпитализации'},
        ),
        migrations.AddField(
            model_name='hospitalizationepisode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parametercode',
            name='is_numeric',
            field=models.BooleanField(default=True, verbose_name='Числовой?'),
        ),
        migrations.AlterField(
            model_name='medicaltest',
            name='test_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата проведения теста'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='core.hospitalizationepisode', verbose_name='Эпизод госпитализации'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='parameter',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='core.parametercode', verbose_name='Показатель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observation',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Значение'),
        ),
    ]
